---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend1
          image: [여기에 frontend1 이미지 주소 입력]
          ports:
            - containerPort: 3000
        - name: frontend2
          image: [여기에 frontend2 이미지 주소 입력]
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - name: frontend1-port
      protocol: TCP
      port: 3000
      targetPort: 3000
    - name: frontend2-port
      protocol: TCP
      port: 3001
      targetPort: 3000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              name: frontend1-port
      - path: /owner
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              name: frontend2-port
